DeclareModule Localization
  Declare.s Text(Key.s)
EndDeclareModule

Module Localization
  Procedure.s Text(Key.s)
    Select Key
      Case "missing_database"
        ProcedureReturn "Не указан обязательный параметр --database."
      Case "file_missing"
        ProcedureReturn "Файл базы данных не найден."
      Case "open_failed"
        ProcedureReturn "Не удалось открыть базу данных только для чтения."
      Case "usage"
        ProcedureReturn "Использование: ManBaseValidator.exe --database <путь> [--report <путь>] [--format text|json]"
      Case "unknown_argument"
        ProcedureReturn "Неизвестный параметр командной строки."
      Case "missing_value"
        ProcedureReturn "После параметра отсутствует значение."
      Case "gui_title"
        ProcedureReturn "ManBase Validator " + ValidatorVersion::#CLIENT_VERSION
      Case "gui_database"
        ProcedureReturn "База данных:"
      Case "gui_browse"
        ProcedureReturn "Обзор…"
      Case "gui_validate"
        ProcedureReturn "Проверить"
      Case "gui_save_json"
        ProcedureReturn "Сохранить JSON"
      Case "gui_save_text"
        ProcedureReturn "Сохранить текст"
      Case "gui_ready"
        ProcedureReturn "Выберите SQLite-базу для проверки."
      Case "gui_running"
        ProcedureReturn "Проверка выполняется…"
      Case "gui_select_database"
        ProcedureReturn "Выберите базу ManBase"
      Case "gui_database_filter"
        ProcedureReturn "SQLite (*.sqlite)|*.sqlite|Все файлы (*.*)|*.*"
      Case "gui_report_filter_json"
        ProcedureReturn "JSON (*.json)|*.json|Все файлы (*.*)|*.*"
      Case "gui_report_filter_text"
        ProcedureReturn "Текст (*.txt)|*.txt|Все файлы (*.*)|*.*"
      Case "gui_save_report"
        ProcedureReturn "Сохранить отчёт"
      Case "gui_default_report"
        ProcedureReturn "validation-report"
      Case "gui_no_database"
        ProcedureReturn "Сначала выберите файл базы данных."
      Case "gui_saved"
        ProcedureReturn "Отчёт сохранён."
      Case "gui_save_failed"
        ProcedureReturn "Не удалось сохранить отчёт."
      Case "gui_status"
        ProcedureReturn "Статус"
      Case "gui_severity"
        ProcedureReturn "Уровень"
      Case "gui_code"
        ProcedureReturn "Код"
      Case "gui_message"
        ProcedureReturn "Сообщение"
      Case "gui_context"
        ProcedureReturn "Контекст"
      Case "gui_details"
        ProcedureReturn "Подробности выбранной проверки:"
      Case "gui_counts"
        ProcedureReturn "Страницы: %pages%   Секции: %sections%   Aliases: %aliases%   FTS: %fts%"
      Case "gui_result"
        ProcedureReturn "Результат: "
      Case "gui_warning_count"
        ProcedureReturn "Предупреждений: "
      Case "gui_error_count"
        ProcedureReturn "Ошибок: "
    EndSelect
    ProcedureReturn Key
  EndProcedure
EndModule
